# Generated by Django 2.2.4 on 2019-08-26 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='pdf',
            new_name='archivo',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='author',
            new_name='autor',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='title',
            new_name='titulo',
        ),
    ]
