# Generated by Django 2.2.4 on 2019-08-26 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190825_2124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='autor',
            new_name='objetivo',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='titulo',
            new_name='tema',
        ),
        migrations.AddField(
            model_name='book',
            name='clase',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
